apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  NEXT_PUBLIC_HOST: {{ .Values.configMap.host | quote }}
  NEXT_PUBLIC_CONFIG_VALUE: {{ .Values.configMap.configValue | quote }}