replicaCount: 1

image:
  repository: yggdrasill/next-configmap
  tag: 0.1.1
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30080

configMap:
  host: "dev.example.com"
  configValue: "Development Environment"

ingress:
  host: "dev.example.com"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi 